config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :users
root 'shops#index'
get 'shops/image_check' => 'shops#image_check'
get 'shops/map' => 'shops#map'
resources :shops

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :users
  validates :shop_name, presence: { :message => "Shop Name Can't be blank"}
  validates :shop_address, presence: { :message => "Shop Address Can't be blank"}
  validates :shop_description, presence: { :message => "Shop Description Can't be blank"}
  validates :avatar, presence: { :message => "Shop Image is mandatory"}


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shops       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    shops_path
 end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = current_user.shops


  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
   @shop.user_id = current_user.id
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else

        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image_check

  @shop = Shop.find_by_id(params[:format])

  end

 def map

   @shop = Shop.find_by_id(params[:format])
   @lat_lang = Geocoder.search(@shop.shop_address )
   @lat =  @lat_lang.present? ? @lat_lang[0].latitude : 34.513299
   @lang = @lat_lang.present? ? @lat_lang[0].longitude : -94.1628807
   @address =  @lat_lang.present? ? @lat_lang[0].formatted_address : @shop.shop_address
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop

      @shop = Shop.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params

       params.require(:shop).permit(:shop_name,:shop_address,:shop_description,:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/_header_shop.html.erb
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>    |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

app/views/layouts/_side_bar.html.erb
<div class="page-sidebar-wrapper">
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse">
		<!-- BEGIN SIDEBAR MENU -->
		<ul class="page-sidebar-menu " data-auto-scroll="true" data-slide-speed="200">
			<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
			<li class="sidebar-toggler-wrapper">
				<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
				<br />
				<br />
				<!-- END SIDEBAR TOGGLER BUTTON -->
			</li>
			<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->

			<li class="<%= (params[:controller] == "shops" and params[:action] == "index") ? "active open" : "" %>">
				<a href=<%= shops_path %> data-no-turbolink="true" id="ad"> <i class="icon-home"></i> <span class="title">Shops</span></a>
			</li>


		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
</div>
<!-- END SIDEBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="page-header-fixed page-quick-sidebar-over-content">

    <% if user_signed_in? %>
  	<%= render :partial => "layouts/header_shop" %>
    <%end%>

  	<div></div>
  	<!-- BEGIN CONTAINER -->
  	<div class="page-container">

    	<%= yield %>
  	</div>
  	<!-- END CONTAINER -->

  </div>
</body>
</html>

app/views/layouts/shop.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Task" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Task</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>
    <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row">
  	<div class="col-md-2">
  		Shop Name :
  	</div>
  	<div class="col-md-6">
  		  <%=  f.text_field :shop_name,:class => 'form-control'  %>
  	</div>
  	<div class="col-md-1"></div>
  </div>
  <div class="row">
  	<div class="col-md-2">

  	</div>
  	<div class="col-md-6">

  	</div>
  	<div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="col-md-2">
      Shop Address  :
    </div>
    <div class="col-md-6">
        <%=  f.text_field :shop_address,:class => 'form-control' %>
    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-6">

    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
  	<div class="col-md-2">
  		Shop Description :
  	</div>
  	<div class="col-md-6">
  		<%=  f.text_field :shop_description, :class => 'form-control' %>
  	</div>
  	<div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-6">

    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="col-md-2">
      Shop Image :
    </div>
    <div class="col-md-6">
      <%= f.file_field :avatar,:class => 'form-control' %>
    </div>
    <div class="col-md-1"></div>
  </div>
  <div class="row">
  	<div class="col-md-2">

  	</div>
  	<div class="col-md-6">

  	</div>
  	<div class="col-md-1"></div>
  </div>
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-6">

    </div>
    <div class="col-md-1"></div>
  </div><br /> <br /> 
  <div class="row">
    <div class="col-md-2">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
    <div class="col-md-6">
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path, :class => 'btn btn-default' %>
    </div>
    <div class="col-md-1"></div>
  </div>






<% end %>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/image_check.html.erb
<div class="page-header">
  <h1>Shop Details</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Shop Name</th>
      <th>Shop Address</th>
      <th>Shop Image</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

      <tr>
        <td><%=  @shop.shop_name %></td>
        <td><%= @shop.shop_address %></td>
        <td ><%= image_tag(@shop.avatar) %> </td>
        <td>
          <%= link_to t('.back', :default => t("helpers.links.back")),
                        shops_path, :class => 'btn btn-default'  %>

        </td>
      </tr>

  </tbody>
</table>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%if @shops.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Shop Name</th>
      <th>Shop Address</th>
      <th>Shop Image</th>
      <th>Map</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

    <% @shops.each do |shop| %>
      <tr>
        <td class="align-center"><%=  shop.shop_name %></td>
        <td class="align-center"><%= shop.shop_address %></td>
        <td class="align-center"><%= link_to ' ', shops_image_check_path(shop.id),:class => "fa fa-picture-o" %> </td>
        <td class="align-center"><%= link_to ' ', shops_map_path(shop.id) ,:class => "fa fa-location-arrow",:target=>"_blank"%> </td>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.new")),
                      new_shop_path,
                      :class => 'btn btn-primary' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-default ' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn  btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>
<%end%>

app/views/shops/map.html.erb
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>



</div>
<script>

var map = new google.maps.Map(document.getElementById('map'), {

    zoom: 12,
    // center: new google.maps.LatLng(-33.92, 151.25),
    center: new google.maps.LatLng('<%= @lat %>', '<%= @lang %>'),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var infowindow = new google.maps.InfoWindow();

  var marker, i;

  for (i = 0; i < 1; i++) {
       marker = new google.maps.Marker({
        position: new google.maps.LatLng('<%= @lat %>', '<%= @lang %>'),
         map: map
       });

       google.maps.event.addListener(marker, 'click', (function(marker, i) {
         return function() {
           infowindow.setContent('<%= @address%>', '<%= @address %>');
           infowindow.open(map, marker);
         }
       })(marker, i));
     }



</script>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
              <div class="page-header">
                <h1>Shop Details</h1>
              </div>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Shop Name</th>
                    <th>Shop Address</th>
                    <th>Shop Image</th>
                    <th>Map </th>
                    <th><%=t '.actions', :default => t("helpers.actions") %></th>
                  </tr>
                </thead>
                <tbody>

                    <tr>
                      <td><%=  @shop.shop_name %></td>
                      <td><%= @shop.shop_address %></td>
                      <td><%= link_to '', shops_image_check_path(@shop.id),:class => "fa fa-picture-o " %> </td>
                      <td><%= link_to '', shops_map_path(@shop.id) ,:class => "fa fa-location-arrow ",:target=>"_blank"%> </td>
                      <td>
                        <%= link_to t('.back', :default => t("helpers.links.back")),
                                      shops_path, :class => 'btn btn-default'  %>
                        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                      edit_shop_path(@shop), :class => 'btn btn-default' %>
                        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                      shop_path(@shop),
                                      :method => 'delete',
                                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                      :class => 'btn btn-danger' %>

                      </td>
                    </tr>

                </tbody>
              </table>